import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const plusJakartaSans = localFont({
  src: [
      {path:"../public/Fonts/PlusJakartaSans-Regular.ttf", weight: "400", style: "normal"},
      {path:"../public/Fonts/PlusJakartaSans-Medium.ttf", weight: "500", style: "normal"},
      {path:"../public/Fonts/PlusJakartaSans-SemiBold.ttf", weight: "600", style: "normal"},
      {path:"../public/Fonts/PlusJakartaSans-Bold.ttf", weight: "700", style: "normal"},
      {path:"../public/Fonts/PlusJakartaSans-ExtraBold.ttf", weight: "800", style: "normal"},
      {path:"../public/Fonts/PlusJakartaSans-Italic.ttf", weight: "400", style: "italic"},
      {path:"../public/Fonts/PlusJakartaSans-MediumItalic.ttf", weight: "500", style: "italic"},
      {path:"../public/Fonts/PlusJakartaSans-SemiBoldItalic.ttf", weight: "600", style: "italic"},
  ],
  variable: "--font-plus-jakarta-sans",
  display: "swap",
});

const bebasNeue = localFont({
  src: [{ path: "../public/Fonts/BebasNeue-Regular.ttf", weight: "400", style: "normal" }],
  variable: "--font-bebas",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Boardroom Bandit",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.variable} ${bebasNeue.variable} antialiased`}>
        <div className="mx-auto  sm:max-w-xl md:max-w-3xl lg:max-w-5xl xl:max-w-7xl">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
